name: Daily Python Script

on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 2 AM UTC (adjust as needed)
  workflow_dispatch:      # Allows manual run from GitHub Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Optional

      - name: Run Python Script
        run: python main.py
